version: '3.6'

# Docker-Compose 单容器使用参考 YAML 配置文件
# 更多配置参数请参考镜像 README.md 文档中说明
services:
  prometheus1:
    image: 'colovu/prometheus:latest'
    ports:
      - '9091:9090'

  prometheus2:
    image: 'colovu/prometheus:latest'
    ports:
      - '9092:9090'

  prometheus3:
    image: 'colovu/prometheus:latest'
    ports:
      - '9093:9090'

networks:
  back-tier:
    driver: bridge
