version: '3.8'

# 伪集群方式配置时，各服务对外暴露的端口在映射到主机时，需要使用不同的端口，否则会导致端口冲突

# Docker-Compose 方式启动容器集群的 YAML 配置文件
# 当前配置仅保证可以启动容器；更多配置参数请参考镜像 README.md 文档中说明
services:
  prometheus1:
    image: 'registry.cn-shenzhen.aliyuncs.com/colovu/prometheus:latest'
    ports:
      - '9091:9090'

  prometheus2:
    image: 'registry.cn-shenzhen.aliyuncs.com/colovu/prometheus:latest'
    ports:
      - '9092:9090'

  prometheus3:
    image: 'registry.cn-shenzhen.aliyuncs.com/colovu/prometheus:latest'
    ports:
      - '9093:9090'

networks:
  back-tier:
    driver: bridge
