version: '3.8'

# Docker-Compose 单容器使用参考 YAML 配置文件
# 更多配置参数请参考镜像 README.md 文档中说明
services:
  prometheus:
    image: 'registry.cn-shenzhen.aliyuncs.com/colovu/prometheus:2.19'
    ports:
      - '9090:9090'
